language: perl
matrix:
    fast_finish: true
perl:
  - '5.8'
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
addons:
   postgresql: "9.3"
env:
  - DB_TESTING: 1
before_install:
   - "cpanm -qn DBI"
   - "cpanm -qn DBD::Pg"
   - "cpanm -qn Try::Tiny"
   - "cpanm -qn Memoize"
   - "cpanm -qn Text::CSV"
   - "cpanm -qn Test::More"
   - "cpanm -qn Test::Requires::Git"
   - "cpanm -qn Devel::Cover::Report::Codecov"

script:
   export RELEASE_TESTING=1 && perl Makefile.PL && make test && cover -test -report codecov
